### ISSUE TITLE
Styles Directory

### ISSUE THREAD

**Issue by alfonsotech** [andybeers/portfolio#7]
Here, you have spaces between each rule set. This seems inconsistent with your practices in the HTML file. I like it that you added comments to your .css files and created sections for the categories there - that is useful.

**Comment by andybeers** [comment]
Interesting question! So far I've only seen CSS written with line-breaks between rules, but I'm open to exploring other styles.

I did a little bit of digging, and found [this google CSS styleguide](https://google.github.io/styleguide/htmlcssguide.xml) in which they recommend:

> Rule Separation
>   -Separate rules by new lines.

Air Bnb also seems to recommend this [in their styleguide](https://github.com/airbnb/css#formatting):

> Put blank lines between rule declarations
