### ISSUE TITLE
Scripts Directory

### ISSUE THREAD

**Issue by alfonsotech** [andybeers/portfolio#8]
In your tabs.js file, lines 3-11,

```
tabs.handleMainNav = function () {
  $('.main-nav .tab').on('click', function() {
    $('.tab-content').hide();
    if ($(this).attr('data-category') === 'portfolio') {
      $('#portfolio').fadeIn();
    } else if ($(this).attr('data-category') === 'about') {
      $('#about').fadeIn();
    }
  });
```

you achieve the same goal but writing it differently from the example outlined in class. It would have been my instinct to do it this way as well, as it seems simpler and more intuitive to me, but I think we were supposed to do it a specific way? That's all, I'm just wondering about this... All in all, your code looks tight and works - I haven't found any missing or extra details. Congrats!

**Comment by andybeers** [comment]
Great catch! When we went over this concept in class and used jQuery to target the specific data property value, I felt silly for starting with the "iterate through everything" approach. Function updated to target the data property directly.
